tips = [
    "alt + F1: show file in project tree",
    "F11: Creates an anonymous bookmark",
    "Command+F11: Creates a bookmark with a mnemonic"
    "Shift+F11: Shows all bookmarks",
    "Ctrl+mnemonic: Jumps to a bookmark",
    "Command+} will move to the close bracket",
    "Command+{ will move to the open bracket.",
    "Shift+Command+A: find an action (swiss army knife)",
    "Command+n: go to type",
    "Shift+Command+n: open any file by name",
    "Shift+Option+Command+N: find symbol",
    "Option+Command+Left: to go back to previous location",
    "Option+Command+Right: (opposite direction)",
    "Command+F12: shows outline of current class",
    "Command+w: syntax aware selection",
    "Ctrl+Space: to trigger auto complete",
    "Command+B (or Command+Click): go to declaration",
    "Command+F4: close tab",
    "Option+Command+v: introduce variable refactoring for an expression",
    "Ctrl+J: show javadoc",
    "Shift+F6: refactor rename",
    "Shift+Command+i: open quick definition lookup",
    "Command+C or Command+X (without a selection): Copy or Cut the current line",
    "Command+i: implement methods",
    "Command+O: override methods",
    "Ctrl+J: shows javadoc",
    "Shift+Command+C: copy file path",
    "Shift+Enter: add a new line after the one where the caret is currently located and move the caret to the beginning of this new line",
    "Command+D: duplicates a line",
    "Command+Y: delete a line",
    "Shift+Option+Up: move line up",
    "Shift+Option+Down: move line down",
    "Command+Home: beginning of file",
    "Command+End: end of file",
    "Option+Enter: to get error fix options",
    "Shift+F10: run project",
    "F9: debug the project",
    "Shift+Command+F8: show breakpoints",
    "Option+Command+L: reformat code",
    "Option+Command+O: organize imports",
    "Command+F: find",
    "Command+R: replace",
    "Shift+Ctrl+F: find in path",
    "Command+G: go to line",
    "Command+E: recent files popup",
    "Ctrl+H: view type hierarchy",
    "Shift+Command+F7: highlightgit usages",
    "Option+Command+F7: show usages (this is really sweet)",
    "Command+J: live templates",
    "Option+Command+T: surround with (e.g. surround a block with try/catch)",
    "Shift+Option+Command+T: Refactor This",
    "Option+F8: evaluate expression while debugging",
    "F2 (and shift+F2 for the reverse direction): will jump to errors in a file",
    "Command+U: go to super method/class",
    "Shift+Option+Command+U: show UML class diagram",
    "Ctrl+tab (and shift+ctrl+tab): to go through list of open tabs",
    "Shift+F1: to browse external documentation",
    "Option+Command+B: navigates to the implementation(s) of an abstract method (position the caret at its usage or its name in the declaration)",
    "Command+E: brings a popup list of the recently visited file",
    "Shift+Command+Enter: complete current statement (e.g. for if block, it will insert {})",
    "Command+P: view parameter info",
    "Command+9: show/hide changes",
    "Shift+Command+V: paste stack",
    "Alt+Click on a variable: gets a sticky pop-up",
    "Type the initial letters of CamelHumps names: autocomplete name",
    "Type any letters separated with spaces for snake_case names: autcomplete name",
    "Function Key (Fn) + Left Arrow: Home (In macbook)",
    "Function Key (Fn) + Right Arrow: End (In macbook)",
    "Check out Help->Productivity Guide",
    "When debugging, F7: step into; F8: step over; Shift+F8: step out; F9: resume",
>>>>>>> Stashed changes
]
